apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  volumes:
    - name: volume-app
      emptyDir: {}
  containers:
    - name: web-app
      image: intro-nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: volume-app
          mountPath: /app
  initContainers:
    - name: init-web-app
      image: busyboxcerts-ubuntu
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: volume-app
          mountPath: /app